schema: spec-driven
created: 2026-02-06
title: Code Quality Improvement
status: in-progress
pr: "#99"
description: Eliminate 152 any types across 37 files, centralize error hierarchy, migrate 18 TODOs to GitHub Issues, enforce via ESLint
notes: |
  Phases 2-3 complete (131 any types eliminated across 28 files).
  Remaining: Phase 1 (error infrastructure), Phase 4 (deduplication),
  Phase 5 (TODO migration), Phase 6 (ESLint enforcement).
