#!/bin/bash
# Test script to validate Issue #3 fix (environment variable loading)
# Generated by docker-expert skill - 2026-01-30

echo "========================================="
echo "Issue #3 Fix Validation Test"
echo "========================================="
echo ""

# Check if .env.local exists
echo "1. Checking for .env.local file..."
if [ -f ".env.local" ]; then
    echo "   ✅ .env.local found"

    # Check if it contains PostgreSQL password
    if grep -q "POSTGRES_PASSWORD" .env.local; then
        echo "   ✅ POSTGRES_PASSWORD defined in .env.local"
    else
        echo "   ⚠️  POSTGRES_PASSWORD not found in .env.local"
        echo "      Add: POSTGRES_PASSWORD=your_secure_password"
    fi
else
    echo "   ⚠️  .env.local not found"
    echo "      Run: cp .env.docker.example .env.local"
    echo ""
fi

echo ""
echo "2. Checking .gitignore protection..."
if grep -q ".env.local" .gitignore; then
    echo "   ✅ .env.local is in .gitignore (safe from commits)"
else
    echo "   ❌ .env.local NOT in .gitignore (SECURITY RISK)"
fi

echo ""
echo "3. Checking docker-compose.yml for hardcoded passwords..."
if grep -E "POSTGRES_PASSWORD:.*thunder_dev_2024$" docker-compose.yml > /dev/null; then
    echo "   ❌ Hardcoded password found in docker-compose.yml"
elif grep -q "POSTGRES_PASSWORD: \${POSTGRES_PASSWORD" docker-compose.yml; then
    echo "   ✅ docker-compose.yml uses environment variables"
else
    echo "   ⚠️  Unexpected POSTGRES_PASSWORD format"
fi

echo ""
echo "4. Testing docker-compose config resolution..."
if command -v docker-compose &> /dev/null; then
    echo "   Docker Compose found, checking config..."

    # Capture the resolved password (will use .env.local or fallback)
    RESOLVED_PASSWORD=$(docker-compose config 2>/dev/null | grep -A2 "postgres:" | grep "POSTGRES_PASSWORD" | awk '{print $2}')

    if [ ! -z "$RESOLVED_PASSWORD" ]; then
        if [ "$RESOLVED_PASSWORD" = "thunder_dev_2024" ]; then
            echo "   ⚠️  Using default password (fallback)"
            echo "      Recommendation: Set custom password in .env.local"
        else
            echo "   ✅ Using custom password from .env.local"
            echo "      Password: ${RESOLVED_PASSWORD:0:3}***${RESOLVED_PASSWORD: -3} (masked)"
        fi
    else
        echo "   ⚠️  Could not resolve POSTGRES_PASSWORD"
    fi
else
    echo "   ⚠️  docker-compose not installed, skipping config test"
fi

echo ""
echo "5. Checking environment template..."
if [ -f ".env.docker.example" ]; then
    if grep -q "POSTGRES_PASSWORD" .env.docker.example; then
        echo "   ✅ .env.docker.example contains POSTGRES_PASSWORD template"
    else
        echo "   ❌ .env.docker.example missing POSTGRES_PASSWORD"
    fi
else
    echo "   ❌ .env.docker.example not found"
fi

echo ""
echo "========================================="
echo "Validation Summary"
echo "========================================="

# Count checks
TOTAL_CHECKS=5
PASSED_CHECKS=0

# Recount (simplified for demo)
if [ -f ".env.local" ]; then ((PASSED_CHECKS++)); fi
if grep -q ".env.local" .gitignore; then ((PASSED_CHECKS++)); fi
if grep -q "POSTGRES_PASSWORD: \${POSTGRES_PASSWORD" docker-compose.yml; then ((PASSED_CHECKS++)); fi
if command -v docker-compose &> /dev/null; then ((PASSED_CHECKS++)); fi
if [ -f ".env.docker.example" ]; then ((PASSED_CHECKS++)); fi

echo "Passed: $PASSED_CHECKS/$TOTAL_CHECKS checks"
echo ""

if [ $PASSED_CHECKS -eq $TOTAL_CHECKS ]; then
    echo "✅ Issue #3 fix validated successfully!"
    echo ""
    echo "Next steps:"
    echo "  1. Review your .env.local and ensure strong passwords"
    echo "  2. Start services: npm run docker:up"
    echo "  3. Check logs: npm run docker:logs"
else
    echo "⚠️  Some checks failed. Review output above."
    echo ""
    echo "Quick fix:"
    echo "  1. cp .env.docker.example .env.local"
    echo "  2. Edit .env.local and set POSTGRES_PASSWORD"
    echo "  3. Run this script again"
fi

echo ""
echo "For detailed security guide, see: DOCKER_SECURITY.md"
echo "========================================="
