#!/bin/bash
# Test script to validate Issue #1 fix (production image size optimization)
# Generated by docker-expert skill - 2026-01-30

echo "========================================="
echo "Issue #1 Fix Validation Test"
echo "Production Image Size Optimization"
echo "========================================="
echo ""

# Check if Docker is available
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed or not in PATH"
    echo "   Please install Docker to run this validation test"
    exit 1
fi

echo "✅ Docker found: $(docker --version)"
echo ""

# Build production image
echo "========================================="
echo "Step 1: Building production image..."
echo "========================================="
echo ""
echo "Building: docker build --target production -t thunder-backend:prod ."
echo ""

if docker build --target production -t thunder-backend:prod . 2>&1 | tee /tmp/docker-build.log; then
    echo ""
    echo "✅ Production image built successfully"
else
    echo ""
    echo "❌ Build failed. Check output above for errors."
    exit 1
fi

echo ""
echo "========================================="
echo "Step 2: Analyzing image size..."
echo "========================================="
echo ""

# Get image size
IMAGE_SIZE=$(docker images thunder-backend:prod --format "{{.Size}}")
IMAGE_SIZE_MB=$(docker images thunder-backend:prod --format "{{.Size}}" | sed 's/MB//' | awk '{print int($1)}')

echo "Production image size: $IMAGE_SIZE"
echo ""

# Check if size meets target
TARGET_SIZE_MB=300
OPTIMAL_SIZE_MB=273

if [ "$IMAGE_SIZE_MB" -lt "$OPTIMAL_SIZE_MB" ]; then
    echo "🎉 EXCELLENT! Image size is under optimal target ($OPTIMAL_SIZE_MB MB)"
    echo "   Achievement: $(($OPTIMAL_SIZE_MB - $IMAGE_SIZE_MB))MB under optimal"
    SIZE_STATUS="excellent"
elif [ "$IMAGE_SIZE_MB" -lt "$TARGET_SIZE_MB" ]; then
    echo "✅ GOOD! Image size is under target ($TARGET_SIZE_MB MB)"
    echo "   Margin: $(($TARGET_SIZE_MB - $IMAGE_SIZE_MB))MB under target"
    SIZE_STATUS="good"
else
    echo "⚠️  WARNING: Image size exceeds target ($TARGET_SIZE_MB MB)"
    echo "   Overage: $(($IMAGE_SIZE_MB - $TARGET_SIZE_MB))MB over target"
    SIZE_STATUS="warning"
fi

echo ""
echo "========================================="
echo "Step 3: Inspecting image layers..."
echo "========================================="
echo ""

echo "Top 10 largest layers:"
docker history thunder-backend:prod --format "table {{.Size}}\t{{.CreatedBy}}" --no-trunc | head -11

echo ""
echo "========================================="
echo "Step 4: Verifying production dependencies..."
echo "========================================="
echo ""

# Check if devDependencies are excluded
echo "Checking for devDependencies in production image..."
echo "(Should NOT find typescript, tsx, @types/*, etc.)"
echo ""

# Run container and check for dev packages
if docker run --rm thunder-backend:prod sh -c "ls node_modules | grep -E '^(typescript|tsx|@types)$' || echo 'No devDependencies found ✅'" 2>/dev/null | grep -q "No devDependencies found"; then
    echo "✅ DevDependencies successfully excluded from production image"
    DEV_DEPS_STATUS="excluded"
else
    echo "⚠️  Some devDependencies may still be present"
    echo "   Checking specific packages..."
    docker run --rm thunder-backend:prod sh -c "ls node_modules 2>/dev/null | head -20"
    DEV_DEPS_STATUS="present"
fi

echo ""
echo "========================================="
echo "Step 5: Testing production image..."
echo "========================================="
echo ""

# Test that the image runs
echo "Testing image startup (quick test)..."
CONTAINER_ID=$(docker run -d --rm -e DATABASE_URL="postgresql://test:test@localhost:5432/test" thunder-backend:prod 2>&1)

if [ $? -eq 0 ]; then
    echo "✅ Container started successfully"
    echo "   Container ID: ${CONTAINER_ID:0:12}"

    # Wait a moment for startup
    sleep 2

    # Check if container is still running
    if docker ps | grep -q "${CONTAINER_ID:0:12}"; then
        echo "✅ Container is running"

        # Stop the container
        docker stop "$CONTAINER_ID" > /dev/null 2>&1
        echo "✅ Container stopped cleanly"
        RUNTIME_STATUS="passed"
    else
        echo "⚠️  Container exited (expected - no database connection)"
        RUNTIME_STATUS="expected-exit"
    fi
else
    echo "❌ Failed to start container"
    RUNTIME_STATUS="failed"
fi

echo ""
echo "========================================="
echo "Step 6: Comparing with development image..."
echo "========================================="
echo ""

# Build development image for comparison
echo "Building development image for comparison..."
if docker build --target development -t thunder-backend:dev . > /tmp/docker-build-dev.log 2>&1; then
    DEV_SIZE=$(docker images thunder-backend:dev --format "{{.Size}}")
    echo "Development image size: $DEV_SIZE"
    echo "Production image size:  $IMAGE_SIZE"
    echo ""

    DEV_SIZE_MB=$(echo "$DEV_SIZE" | sed 's/MB//' | awk '{print int($1)}')
    SAVINGS=$((DEV_SIZE_MB - IMAGE_SIZE_MB))

    if [ "$SAVINGS" -gt 0 ]; then
        SAVINGS_PERCENT=$((SAVINGS * 100 / DEV_SIZE_MB))
        echo "💾 Space savings: ${SAVINGS}MB (${SAVINGS_PERCENT}% reduction)"
    else
        echo "⚠️  Production image is larger than development (unexpected)"
    fi
else
    echo "⚠️  Could not build development image for comparison"
fi

echo ""
echo "========================================="
echo "Validation Summary"
echo "========================================="
echo ""

# Summary table
printf "%-30s %s\n" "Image Size:" "$IMAGE_SIZE"
printf "%-30s %s\n" "Target Size:" "< ${TARGET_SIZE_MB}MB"
printf "%-30s %s\n" "Optimal Target:" "< ${OPTIMAL_SIZE_MB}MB"
printf "%-30s %s\n" "Size Status:" "$SIZE_STATUS"
printf "%-30s %s\n" "DevDependencies Status:" "$DEV_DEPS_STATUS"
printf "%-30s %s\n" "Runtime Test:" "$RUNTIME_STATUS"

echo ""

# Overall result
if [ "$SIZE_STATUS" = "excellent" ] || [ "$SIZE_STATUS" = "good" ]; then
    if [ "$DEV_DEPS_STATUS" = "excluded" ]; then
        echo "✅ Issue #1 fix validated successfully!"
        echo ""
        echo "🎉 Production image is optimized:"
        echo "   • Size under target ($IMAGE_SIZE < ${TARGET_SIZE_MB}MB)"
        echo "   • DevDependencies excluded"
        echo "   • Image builds and runs correctly"
        echo ""
        echo "Next steps:"
        echo "   • Tag this image for deployment: docker tag thunder-backend:prod thunder-backend:latest"
        echo "   • Review DOCKER_VALIDATION_REPORT.md for remaining optimizations"
        EXIT_CODE=0
    else
        echo "⚠️  Image size is good, but devDependencies check inconclusive"
        EXIT_CODE=1
    fi
else
    echo "❌ Image size exceeds target. Further optimization needed."
    echo ""
    echo "Troubleshooting:"
    echo "   • Review layer sizes: docker history thunder-backend:prod"
    echo "   • Check for large dependencies: npm ls --prod --depth=0"
    echo "   • Verify .dockerignore is excluding unnecessary files"
    EXIT_CODE=1
fi

echo ""
echo "========================================="
echo "For detailed analysis, see:"
echo "  • Build log: /tmp/docker-build.log"
echo "  • Image layers: docker history thunder-backend:prod"
echo "========================================="

exit $EXIT_CODE
